### ISSUE TITLE
Blank lines when writing a PDB

### ISSUE THREAD

**Issue by DomML** [Eigenstate/vmd-python#29]
Hello,
I notice the insertion of blank line between ATOM lines when writing a PDB.
Original : 
![image](https://user-images.githubusercontent.com/25391513/67376609-bbfe3c80-f584-11e9-9290-d37366f8d058.png)
vmd writen : 
![image](https://user-images.githubusercontent.com/25391513/67376666-d801de00-f584-11e9-96f8-2477c3636c5e.png)

**Comment by jvermaas** [comment]
Do you have the .pdb files handy? Images lie, and this might just be a line-wrapping feature making it appear like something it is not.

**Comment by Eigenstate** [comment]
I agree with @jvermaas, it looks like the width of your text editor is such that the lines are wrapping.
If there's a problem with Dabble not running or producing output that doesn't make sense, reopen this issue with a detailed description of the inputs and outputs and I can take look.

**Comment by DomML** [comment]
it is not an issue with the editor : 
![image](https://user-images.githubusercontent.com/25391513/67457640-887aeb00-f634-11e9-98a0-f4ffad59538a.png)


[TAA-aa-all.pdb.txt](https://github.com/Eigenstate/vmd-python/files/3765939/TAA-aa-all.pdb.txt)
[test0.pdb.txt](https://github.com/Eigenstate/vmd-python/files/3765940/test0.pdb.txt)

**Comment by jvermaas** [comment]
Weird. What is the extra non-standard stuff in your pdb? It could be that your oddly formatted pdb means that VMD sees a newline in a column where it expects data and as a result writes newlines where it doesn't intend to when writing the data back out. Basically, this isn't a bug with the plugin, since regular VMD will do the same thing. VMD is pretty strict about its input format and output requirements for PDBs, since those are tightly specified. See https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html for what the pdb standard is, since that is what VMD expects. For instance, your input is only 75 columns wide, but the pdb format is 80. That might be why you get 3 spaces in the output.

**Comment by DomML** [comment]
It indeed seems that adding 5 whitespaces at the end of each line lead to a normal vmd written file.
Thank you very much.
