### ISSUE TITLE
Installation error in vmd-python

### ISSUE THREAD

**Issue by saikat0003** [Eigenstate/vmd-python#41]
I have used the following command:
conda install -c conda-forge vmd-python

However, it shows the following error:
(base) saikat@saikat-ROG-Strix:~$ conda install -c conda-forge vmd-python
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): - 

Could please guide me to install the vmd python.
I have tried the other method also. It did not works for me.

**Comment by Eigenstate** [comment]
This is a problem with the conda dependency manager being unable to install the dependencies required by vmd-python in your environment due to requirements of other packages that you have installed. Try creating a new conda environment and installing it there to avoid such conflicts. This is not an issue with vmd-python.

If the other method (I'm guessing you mean `python setup.py install`) does not work, please include a full description of the problem, including the commands you ran and the output generated.

**Comment by saikat0003** [comment]
Now its working fine. Thank you.
Saikat Pal



 

    On Tuesday, 19 July, 2022 at 04:49:46 pm GMT-4, Robin Betz ***@***.***> wrote:  
 
 


This is a problem with the conda dependency manager being unable to install the dependencies required by vmd-python in your environment due to requirements of other packages that you have installed. Try creating a new conda environment and installing it there to avoid such conflicts. This is not an issue with vmd-python.

If the other method (I'm guessing you mean python setup.py install) does not work, please include a full description of the problem, including the commands you ran and the output generated.
