### ISSUE TITLE
Memory bleed (not dumping) issue

### ISSUE THREAD

**Issue by bc118** [Eigenstate/vmd-python#50]
When running vmd.eval("source xxxx.tcl") file, it errors if you have exit at the 'exit' of the xxxx.tcl, like you should.  However, if exit is not there, it just holds all the loaded dcd files (loaded from xxx.tcl) in memory.  Hence if you are doing for loops on files, you run out of memory.

**Comment by jvermaas** [comment]
Pretty sure this is working as designed. If you source a .tcl script that loads a trajectory, it'll do exactly what the tcl script would do, and leave the trajectory loaded. Exit will get you out of the tcl interpreter, but since python is controlling VMD, there is still a molecule there for you to interact with. If you wanted to delete the molecule, you can just do that through the usual delete commands in Python or tcl.

**Comment by Eigenstate** [comment]
@jvermaas is right, this is intended behavior. By having the TCL and Python interpreters operate in the same process, you can manipulate the same molecule with both languages in the same session using its molid. 

To fix your memory leak you can delete the molecules you create when you're finished using them. You could also do this from the Python interface by deleting all loaded molecules in between calls to your TCL script:

```python
from vmd import molecule

for molid in molecule.listall():
  molecule.delete(molid)
```

**Comment by bc118** [comment]
Thanks for the information.  Have a good day
